"""tabla videojuegos actualizar nueva columna

Revision ID: 230d0aaef492
Revises: e23289f5acf7
Create Date: 2026-07-04 20:35:19.776016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230d0aaef492'
down_revision: Union[str, Sequence[str], None] = 'e23289f5acf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videojuegos', sa.Column('developers', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videojuegos', 'developers')
    # ### end Alembic commands ###
