"""actualizar developers en videojuegos

Revision ID: 274eab24b53d
Revises: 3783c1152d35
Create Date: 2026-07-07 13:30:32.346543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '274eab24b53d'
down_revision: Union[str, Sequence[str], None] = '3783c1152d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videojuegos', sa.Column('developers', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videojuegos', 'developers')
    # ### end Alembic commands ###
