"""añadir favoritos a animelogs y videojuegoslogs

Revision ID: 3783c1152d35
Revises: 230d0aaef492
Create Date: 2026-07-06 10:16:43.733032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3783c1152d35'
down_revision: Union[str, Sequence[str], None] = '230d0aaef492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime_logs', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('videojuego_logs', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videojuego_logs', 'is_favorite')
    op.drop_column('anime_logs', 'is_favorite')
    # ### end Alembic commands ###
