"""modificar tablas anime y videojuego

Revision ID: 6196d613fc35
Revises: 3e0e90bac3e7
Create Date: 2026-06-30 12:05:09.742922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6196d613fc35'
down_revision: Union[str, Sequence[str], None] = '3e0e90bac3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animes', sa.Column('genre', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('animes', sa.Column('synopsis', sa.Text(), nullable=True))
    op.add_column('videojuegos', sa.Column('genre', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('videojuegos', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videojuegos', 'description')
    op.drop_column('videojuegos', 'genre')
    op.drop_column('animes', 'synopsis')
    op.drop_column('animes', 'genre')
    # ### end Alembic commands ###
