"""segunda modificacion a tablas animes y videojuegos

Revision ID: c712924c4e58
Revises: 6196d613fc35
Create Date: 2026-07-01 11:30:32.897358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c712924c4e58'
down_revision: Union[str, Sequence[str], None] = '6196d613fc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animes', sa.Column('type', sa.String(), nullable=True))
    op.add_column('animes', sa.Column('aired', sa.String(), nullable=True))
    op.add_column('animes', sa.Column('global_score', sa.Float(), nullable=True))
    op.add_column('videojuegos', sa.Column('released', sa.String(), nullable=True))
    op.add_column('videojuegos', sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('videojuegos', sa.Column('metacritic_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videojuegos', 'metacritic_score')
    op.drop_column('videojuegos', 'platforms')
    op.drop_column('videojuegos', 'released')
    op.drop_column('animes', 'global_score')
    op.drop_column('animes', 'aired')
    op.drop_column('animes', 'type')
    # ### end Alembic commands ###
