"""tabla animes actualizar nuevas columnas

Revision ID: e23289f5acf7
Revises: c712924c4e58
Create Date: 2026-07-04 20:19:32.660065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e23289f5acf7'
down_revision: Union[str, Sequence[str], None] = 'c712924c4e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animes', sa.Column('title_japanese', sa.String(), nullable=True))
    op.add_column('animes', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('animes', sa.Column('studio', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animes', 'studio')
    op.drop_column('animes', 'duration')
    op.drop_column('animes', 'title_japanese')
    # ### end Alembic commands ###
